artist:
  name: Aidan McGowan Jazz
  tagline: Jazz Saxophonist
  # seo_title:
  # seo_description:
  # contact_twitter_username:
  # contact_phone: 
  # contact_email: 

social:
  - name: Facebook
    url: https://www.facebook.com/aidan.mcgowan.376
  - name: Instagram
    url: https://www.instagram.com/aidan_mcgowan251/
  - name: Youtube
    url: https://www.youtube.com/channel/UCmB9dB-XLL_rjaQ8T2yfKYQ

site_language: en
