artist:
  name: Thomas Hinds Media
  tagline: Solo acoustic artist
  # seo_title:
  # seo_description:
  # contact_twitter_username:
  # contact_phone: 
  # contact_email: 

social:
  - name: Facebook
    url: https://www.facebook.com/hindsthomas/
  - name: Instagram
    url: https://instagram.com
  - name: Twitter
    url: https://twitter.com
  - name: Youtube
    url: https://youtube.com
  - name: Spotify
    url: https://spotify.com

site_language: en
